version: '3.8'
services:
  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   ports:
  #     - "2181:2181"
  #   healthcheck:
  #     test: ["CMD-SHELL", "echo ruok | nc -w 2 localhost 2181 || exit 1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  # kafka:
  #   image: wurstmeister/kafka:2.12-2.2.1
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #   volumes:
  #     - ./kafka-healthcheck.sh:/kafka-healthcheck.sh
  #   depends_on:
  #     zookeeper:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD", "sh", "/kafka-healthcheck.sh"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  rabbitmq:
    image: rabbitmq:3.9.5-management
    ports:
      - "5672:5672"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    environment:
      RABBITMQ_HOST: rabbitmq
      # KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ANIME_NAME: ${ANIME_NAME}
      OUTPUT_VIDEO_PATH: ${OUTPUT_VIDEO_PATH}
      AUDIO_PATH: ${AUDIO_PATH}
    depends_on:
      rabbitmq:
        condition: service_healthy
      # kafka:
      #   condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
